version: "3.3"

services:
  hashi-app: &hashi-app
    build: .
    container_name: hashi-app
    restart: "no"
    volumes:
      - hashi_static_data:/hashi/static
    env_file:
      - .hashi.app.env
    command: "/app/entrypoint.sh"
    networks:
      - nginx-proxy

  hashi-rqworker:
    <<: *hashi-app
    container_name: hashi-rqworker
    command: /app/rqworker.entrypoint.sh

  hashi-app-static:
    image: nginx:latest
    container_name: hashi-app-static
    restart: "no"
    volumes:
      - hashi_static_data:/usr/share/nginx/html
    env_file:
      - .hashi.app.static.env
    depends_on:
      - hashi-app
    expose:
      - "80"
    networks:
      - nginx-proxy

  hashi-redis:
    image: redis:latest
    container_name: hashi-redis
    restart: "no"
    expose:
      - "6379"
    volumes:
      - ./redis_data:/data
    networks:
      - nginx-proxy

volumes:
  hashi_static_data:
  redis_data:
    driver: local

networks:
  nginx-proxy:
    external: true
