version: "3.3"

services:
  hashi-app:
    build: .
    container_name: hashi-app
    restart: "no"
    expose:
      - "8182"
    ports:
      - "8182:8182"
    env_file:
      - .hashi.app.env
    command: "/app/entrypoint.sh"
    networks:
      - nginx-proxy
    depends_on:
      - hashi-redis

  hashi-redis:
    image: redis:latest
    container_name: hashi-redis
    restart: "no"
    expose:
      - "6379"
    volumes:
      - ./redis_data:/data
    networks:
      - nginx-proxy

volumes:
  redis_data:
    driver: local

networks:
  nginx-proxy:
    external: true
