# Generated by Django 3.2.9 on 2021-12-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_alter_notification_gateway"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="processed",
        ),
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RECEIVED")], default=1
            ),
        ),
    ]
