# Generated by Django 4.0.2 on 2022-02-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_alter_notification_gateway"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="processed",
        ),
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RECEIVED"), (2, "VERIFIED"), (3, "INVALID")], default=1
            ),
        ),
    ]
