# Generated by Django 3.2.9 on 2021-12-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_auto_20211201_2016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RECEIVED"), (2, "CONFIRMED")], default=1
            ),
        ),
    ]
