# Generated by Django 3.2.9 on 2021-12-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0004_alter_notification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "RECEIVED"), (2, "VERIFIED"), (3, "INVALID")], default=1
            ),
        ),
    ]
