# Generated by Django 3.2.8 on 2021-11-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0002_alter_entry_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "entries"},
        ),
    ]
